= User Provisioned Installation of Red Hat OpenShift 4.x on VMware Virtual Infrastructure
:toc:

== Introduction

Installing OpenShift (OCP) 4.x requires a significant amount of pre-planning and infrastructure preparation.

In this guide we will install a small OpenShift 4.2 instance.  We will use an installation server with an embedded web server.  Our cluster will consist of a bootstrap node, 3 master nodes, 3 worker nodes, 2 load balancers.  The installation server and bootstrap server can be deleted when the installation is complete, however you may want to keep the installation server around for future installs.

This document will contain information for installing in a VMware vSphere environment as well as in a "bare metal" environment.  The reason "bare metal" is in quote is that this installation method will work with any hypervisor/cloud provider.

OCP has specific installers for a number of cloud providers (AWS, Google, IBM Cloud, Azure) known as Installer Provisioned Infrastructure (or IPI) and a separate mechanism for using User Provisioned Infrastructure (UPI).

For UPI, Red Had provides an installer for VMware environments which use vCenter Server and also for bare metal.  If you have any other hypervisor in your on-prem environment than VMware (e.g. KVM or Nutanix) you can use the bare metal installer even though the platform is not technically bare metal.  You will do the installation as though it were bare metal.  You can also use this installer if you want to do an actual bare metal install. :-)

This document will *not* describe doing an IPI installation, but you can still use the bare metal installation method in those environments if you so desire.

Many of the steps to install OCP 4x in a UPI environment are common regardless of your hypervisor or bare metal infrastructure. To make the document more readable, there are collapsible sections for details of the specific environment you are trying to use, VMware or Bare Metal.  Open the expand the appropriate sections for the type of environment you are deploying.

== Terminology

Host:: A physical machine with a hypervisor installed which can be used to host one or more virtual machines.

Server:: A physical or virtual machine that is used to provide services to other machines.

Workstation:: A physical or virtual machine that is typically used by a single person as a desktop on which work can be done.  This is typically a laptop, desktop, or virtual machine provided by some technology such as Citrix.

VM:: A Virtual Machine which can be provisioned as a server or workstation and runs as a "guest" on a "host" machine.

Guest:: Another name for a Virtual Machine.

Node:: A specialized physical or virtual machine dedicated to a specific function.  For example, a "node" could be a Storage Node, Compute Node, Master Node, Worker node, Infrastructure Node, etc.

Installation in a UPI environment includes the following basic steps:

In this guide we will use the following topology:

* Installation server (with webserver installed)
* 1 load balancer for the control control plane (master nodes)
* 1 load balancer for the compute nodes (worker nodes)
* 1 Bootstrap node
* 3 control plane nodes (master nodes)
* 3 compute nodes (worker nodes)

+++ <details><summary> +++
Basic Install Steps for VMware
+++ </summary><div> +++
----
. Create an installation node (running RHEL 7 or 8) an with embedded web server (or reuse an existing server that you have used for a previous install - you can install multiple clusters with a single install server).
. Download and deploy the rhcos template onto your vcenter server.
. Download and explode the openshift installer onto your installation server.
. Create the needed `install-config.yaml` file on your installation server.
. Create the needed ignition files for your deployment
. Deploy, but don't boot the bootstrap, control plane, and compute nodes.
. Configure the DHCP server.
. Configure DNS to support your cluster
. Create or configure a load balancer for the control plane
. Create or configure a load balancer for the compute nodes.
. Complete the bootstrap process
. Configure persistent storage for your image registry
. Complete installation
. Login to your new cluster and configure authentication
----
+++ </div></details> +++

+++ <details><summary> +++
Basic Install Steps for Bare Metal
+++ </summary><div> +++
----
. Create an installation node (running RHEL 7 or 8) an with embedded web server (or reuse an existing server that you have used for a previous install - you can install multiple clusters with a single install server).
. Download and deploy the .img and metal config files from Red Hat.
. Download and explode the openshift installer onto your installation server.
. Create the needed install-config.yaml file on your installation server.
. Create the needed ignition files for your deployment
. Configure the DHCP server
. Configure the PXE server.
. Configure DNS to support your cluster
. Create or configure a load balancer for the control plane
. Create or configure a load balancer for the compute nodes.
. Complete the bootstrap process
. Configure persistent storage for your image registry
. Complete installation
. Login to your new cluster and configure authentication
----
+++ </div></details> +++
